#/bin/sh

URL="http://knowledge:8080"
TOKEN="xKuWT1ArbcFrQR8PxIdUTf2Uk9AmmshMigc5Dq2a7JvsNMlDaAVcCr7xJNDN8n6y"
BASEDIRNAME=/base
CONTENTSDIR=../
PRVIVATE=-private

./runDir.sh $URL $TOKEN $BASEDIRNAME $CONTENTSDIR $PRVIVATE

exit 0;
